### ISSUE TITLE
Loading Forever 

### ISSUE THREAD

**Issue by jeanPokou** [graffiti75/GithubTrending#1]
Hi @graffiti75  I  think I found the issue, that causes the app to loads forever. it is because the cache is empty and repository is trying to retrieve data from it. Take a look at the functon **getProjects** in the Data module **ProjectsDataRepository** 
```kotlin
 override fun getProjects(): Observable<List<Project>> {
        return Observable.zip(cache.areProjectsCached().toObservable(),
                cache.isProjectsCacheExpired().toObservable(),
                BiFunction<Boolean, Boolean, Pair<Boolean, Boolean>> { areCached, isExpired ->
                    Pair(areCached, isExpired)
                })
                .flatMap {
                    factory.getDataStore(it.first, it.second).getProjects().toObservable()
                            .distinctUntilChanged()
                }
                .flatMap { projects ->
                    factory.getCacheDataStore()
                            .saveProjects(projects)
                            .andThen(Observable.just(projects))
                }
                .map {
                    it.map {
                        mapper.mapFromEntity(it)
                    }
                }
    }

```
The **zip**  operators takes two observable  (cache.areProjectsCached() and cache.isProjectsCacheExpired()) which values are true and false,  hence the factory.getDataStore always returns the Cache  and never the Remote . If you replace both of them by  **Observable.just(true)** like this you should get something in recycling view barring any other issues
```kotlin
 override fun getProjects(): Observable<List<Project>> {
        return Observable.zip(
                Observable.just(true),
                Observable.just(true),
                BiFunction<Boolean, Boolean, Pair<Boolean, Boolean>> { areCached, isExpired ->
                    Pair(areCached, isExpired)
                })
                .flatMap {
                    factory.getDataStore(it.first, it.second).getProjects()
                            .distinctUntilChanged()
                }
                .flatMap { projects ->
                    factory.getCacheDataStore()
                            .saveProjects(projects)
                            .andThen(Observable.just(projects))
                }
                .map {
                    it.map {
                        mapper.mapFromEntity(it)
                    }
                }
    }

```
I think the issue is coming from the fact the **getConfig** returns a Flowable. You can read more here [RxRoom](https://medium.com/androiddevelopers/room-rxjava-acb0cd4f3757) and also [Here] (https://gist.github.com/crazyhitty/950b52a7c1bb5ddeaba1814e20aeab6e). You can edit the (cache.areProjectsCached() and cache.isProjectsCacheExpired()) using the above links and fix the test. I hopes it helps you
Ps: A similar issue on [stackoverflow](https://stackoverflow.com/a/45270876/3064295)

**Comment by graffiti75** [comment]
Hello @jeanPokou .

So, my original code for this method is that:

```kotlin
override fun getProjects(): Observable<List<Project>> {
    return Observable.zip(cache.areProjectsCached().toObservable(),
        cache.isProjectsCacheExpired().toObservable(),
        BiFunction<Boolean, Boolean, Pair<Boolean, Boolean>> {
            areCached, isExpired -> Pair(areCached, isExpired)
        })
        .flatMap {
            factory.getDataStore(it.first, it.second).getProjects()
        }
        .flatMap {
            projects -> factory.getCacheDataStore()
            .saveProjects(projects)
            .andThen(Observable.just(projects))
        }
        .map {
            it.map {
                mapper.mapFromEntity(it)
            }
        }
}
```

So there is one different line from my code and the code you pasted above:

```kotlin
factory.getDataStore(it.first, it.second).getProjects()
.toObservable().distinctUntilChanged()
```

This line happens below the first `.flatMap`.

**Comment by graffiti75** [comment]
If I try to run your code, this error happens:

```
/Users/RodrigoCericatto/Desktop/Caster/Android Clean Architecture/From Scratch/GithubTrending/Data/src/main/java/br/cericatto/data/ProjectsDataRepository.kt: (27, 73): Unresolved reference: toObservable
```

**Comment by jeanPokou** [comment]
Yes check again the code, I am passing **Observable.just(true)**, I am not using **toObservable()** here

**Comment by graffiti75** [comment]
@jeanPokou this error keeps happening. See:

[http://bit.ly/2P3lPwh](url)

**Comment by jeanPokou** [comment]
your link is broken

**Comment by graffiti75** [comment]
Don't click into the link.
Copy the link and paste into your browser.  It is a Google Drive link with an image.

**Comment by jeanPokou** [comment]
You right I made a mistake, **getProjects** returns already Observable, I fixed it. You can just removed the toObservable()

**Comment by graffiti75** [comment]
@jeanPokou I tried this new approach, and again, the app still keeps loading forever.

**Comment by jeanPokou** [comment]
@graffiti75  I forked your project I am checking will do a pull request when I find the issue

**Comment by graffiti75** [comment]
Thanks @jeanPokou.
Just one question: do you work for Caster.io or for Joe Birch?

**Comment by jeanPokou** [comment]
No, I am learning android and following the course like you on caster.io and I think we learn faster when helping each other.

**Comment by jeanPokou** [comment]
Are you on slack, maybe we can create a slack channel for the course

**Comment by graffiti75** [comment]
Thanks for your help, @jeanPokou.
I wish I could help more, but really, this Android Clean Architecture is very complex for me.
I am really lost here.

**Comment by graffiti75** [comment]
> Are you on slack, maybe we can create a slack channel for the course

If you want, you can talk to Donn Felker, the creator of Caster.io.
https://caster.io/instructors/donn-felker

**Comment by jeanPokou** [comment]
@graffiti75  found the issue, During the video, I think Joe forgot to add the Gson() converter to 
**makeGithubTrendingService()** in the Remote module. I will fix other issue I can find and do a pull request

**Comment by jeanPokou** [comment]
@graffiti75  pull request sent 👍

**Comment by graffiti75** [comment]
Hello @jeanPokou.
Thanks for your updates! Now the code changes.
Your updates were more effective than Joe's Birch updates! That's outstanding.
Joe is the guy from Caster.io that created this source code into the "Android Clean Architecture" course.
If you agree I can talk to Donn Felker about the possibility of create a Slack for us all.
